version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: infra/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=local
      - PORT=3000
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=yeetest_dev
      - JWT_SECRET=dev-jwt-secret-key
    volumes:
      - ../:/app
      - /app/node_modules
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - yeetest-dev-network
    command: npm run start:dev

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=yeetest_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - yeetest-dev-network

volumes:
  postgres_dev_data:

networks:
  yeetest-dev-network:
    driver: bridge 